### ISSUE TITLE
statemachine执行on_snapshot_save时，LocalSnapshotWriter::snapshot_index返回的值不是最新

### ISSUE THREAD

**Issue by hnwyllmm** [brpc/braft#109]
```
SnapshotWriter* SaveSnapshotDone::start(const SnapshotMeta& meta) {
    _meta = meta;
    return _writer;
}
```
这是在调用_fsm->on_snapshot_save之前，meta中包含了last_applied_index和last_term，记录下来了，但是没有更新_writer的数据，这样statemachine::on_snapshot_save中获取snapshot_index就不是最新的。
writer的meta更新是在on_snapshot_save_done中做的，这样做是故意这样设计的吗？如果是的，为什么不让statemachine::on_snapshot_save获取到最新的snapshot_index？

**Comment by Edward-xk** [comment]
这个问题我的理解可能不全面，所以只说下个人看法：在on_snapshot_save_done中各项操作成功之前，其实是不能保证本次snapshot是成功的，基于此，statemachine即使在on_snapshot_save中获取到snapshot_index也不能代表这是一个“真的”snapshot_index；另外，如果业务层是想获取apply进度，可以在on_apply接口中做些处理

**Comment by hnwyllmm** [comment]
感谢你的解答。与我的问题是一致的。
