### ISSUE TITLE
counter示例里面 怎么返回add后的数据 

### ISSUE THREAD

**Issue by wind-zhang** [brpc/braft#11]
const int64_t prev = _value.fetch_add(detal_value, butil::memory_order_relaxed);  //detal_value=7
请问下  butil::memory_order_relaxed  这个代表的是日志里面的实时数据吗，
这样累加后得到的怎么会是前一次的数据？

192.168.109.128:8100:0 value=0 latency=1922   //第一次累计 之后应该是 7 
192.168.109.128:8100:0 value=7 latency=4504   //第二次累计 之后应该是 14

**Comment by chenzhangyi** [comment]
这个遵循的是c++11里的[atomic接口语义](http://en.cppreference.com/w/cpp/atomic/atomic/fetch_add). 之后的值你加上delta就好了
