### ISSUE TITLE
如果master启动时（log_id=0)已经有数据，怎么保证新加进来的replica也有这些数据？

### ISSUE THREAD

**Issue by hjk41** [brpc/braft#111]
master启动时，它的数据是通过其它方法事先导入的，所以虽然log_id=0，但其实是有数据的。这时如果我直接加replica进去，新的replica并不会load_snapshot，因为log_id=0。有什么办法能够保证replica也能得到导入的那些数据吗？

**Comment by Edward-xk** [comment]
暂时没有这方面的支持，“它的数据是通过其它方法事先导入的”这个应该是非标准做法，个人不太建议这么弄，有没可能转化为log用走状态机同步？如果有特殊性一定要这么干的话，那么三个副本就得“一致”对待了，相当于每个副本都要走一次“导入”过程

**Comment by hnwyllmm** [comment]
可以使用Bootstrap功能，设置log_id非0，每个节点都要经过这个bootstrap

**Comment by hjk41** [comment]
@Edward-xk 数据是批量导入的，如果一个一个写，并且经过raft的话会慢到爆 :-)

按hnwyllmm说的，做了bootstrap，看起来似乎work了。我现在是先调用bootstrap，然后再启动node。

有两个问题请教：
 - 看启动过程，先做了一次save snapshot，然后又load_snapshot，为什么需要load_snapshot这个过程？
 - BootstrapOptions.last_log_index应该设成多少？我设成1，然后发现后加入的replica并不会load_snapshot，设成1024就可以，这个是什么原理？

**Comment by Edward-xk** [comment]
@hjk41 抱歉这个问题下午理解错了，多谢 @hnwyllmm 指正~

- load_snapshot这个是正常的启动流程都有的（不论有没有做bootstrap）,对于有做bootstrap的情况，这个就是把bootstrap过程拉过来的snapshot load到自己的fsm中。
- last_log_index我理解大于0就行，我本地测试是ok的，麻烦你再试下是不是其他什么条件改变了？如果还不符合预期，麻烦给个截图看下

**Comment by hjk41** [comment]
@Edward-xk 又试了一下，last_log_index=1确实是可以的，可能我昨天改了别的地方导致的问题，谢谢~
