### ISSUE TITLE
启动时statemachine::on_leader_start或on_start_following

### ISSUE THREAD

**Issue by hnwyllmm** [brpc/braft#112]
通过WEB页面已经能看到节点的主备状态

**Comment by Edward-xk** [comment]
不好意思，没太get到你问的哪个点。我们的实现里on_leader_start有“之前的log已经apply完成”的语义，而WEB页面上没有这层含义，所以WEB页面的状态会短暂领先于on_leader_start等接口的调用

**Comment by hnwyllmm** [comment]
谢谢，已经回答了我的问题。
更明确点问题就是我在WEB页面上看到raft节点已经裁决出主备，但是我代码里面的on_leader_start和on_start_following没有调用。

**Comment by htner** [comment]
on_leader_start是在on_apply完所有committed log之后才回调的. 估计是这类问题
