### ISSUE TITLE
atomic run server and client error!

### ISSUE THREAD

**Issue by darrenwang00** [brpc/braft#115]
![屏幕快照 2019-03-23 下午4 14 33](https://user-images.githubusercontent.com/7533358/54863691-c3f3c500-4d86-11e9-901c-1edb6cf377f0.png)

client run error!

**Comment by PFZheng** [comment]
gflags 的 -v 重复定义了，这个我确认下

**Comment by ipconfigme** [comment]
这个2月份的时候应该已经修复了，引入是因为一些内部代码在opensource的时候改的不彻底，glog/logging.h与butil/logging.h中v冲突

**Comment by hexiecs** [comment]
> 这个2月份的时候应该已经修复了，引入是因为一些内部代码在opensource的时候改的不彻底，glog/logging.h与butil/logging.h中v冲突

用的是brpc最新的master代码，遇到了同样的问题，请问确认已经修复了吗?

**Comment by hexiecs** [comment]
在brpc编译时加上-DWITH_LOG=1就好了，忽略。
