### ISSUE TITLE
raft节点重启会导致原来已经apply过的日志重新apply一遍

### ISSUE THREAD

**Issue by GTHubT** [brpc/braft#121]
在阅读braft源码中，在raft node节点重启后且重启前没有snapshot情况下，这个节点在下一次apply log的时候会将原来已经apply的log重新apply一遍？
举个例子：log_index从0到10在节点重启之前已经apply过了，当该节点重启后被选举为leader，然后apply新的log index  = 11的entry，会将原来的0到10的entry再apply一遍。

**Comment by ipconfigme** [comment]
重启之后状态机需要恢复上一次的snapshot及其之后的log，如果没有snapshot，应该从全空恢复全部的log，而不是拿重启前的状态机残留数据，再进行重复apply。启动初始化加载的代码是由业务控制的，而不是braft控制。

**Comment by zergvszerg** [comment]
@ipconfigme
看了下data/log, data/raft_meta, data/snapshot里面的pb文件，都没有last applied信息呀，但我把测试集群的3副本一起重启发现"/raft_stat"页面的known_applied_index确实是正确的。请问这个last_applied会被重复apply吗？

**Comment by zergvszerg** [comment]
用example/block测试了一下确实会重复apply，只要写入过程中停集群，来不及snapshot，就会出现重复apply。
