### ISSUE TITLE
能否自动移除掉线的peer?

### ISSUE THREAD

**Issue by hjk41** [brpc/braft#124]
现在有peer掉线之后，leader会一直发“Fail to issue RPC to xxx...”，是否有设置可以在某段时间之后自动移除掉线的peer?

**Comment by ipconfigme** [comment]
braft本身不会自动变更configuration，需要外部进行调用remove_peer

**Comment by hjk41** [comment]
了解。有没有api可以获取哪些peer离线，以及离线了多久？因为braft内部有heartbeat机制，自己的维护一套的话感觉有点重复

**Comment by PFZheng** [comment]
> 了解。有没有api可以获取哪些peer离线，以及离线了多久？因为braft内部有heartbeat机制，自己的维护一套的话感觉有点重复

内部版本有一个 get status 的 api 可以获取复制组的一些状态，基本上和 raft 网页的信息一致，近期会同步到 github。估计能满足你的需要

**Comment by FredyVia** [comment]
请问现在开源版本能够获取哪些掉线节点了吗

> 内部版本有一个 get status 的 api 可以获取复制组的一些状态，基本上和 raft 网页的信息一致，近期会同步到 github。估计能满足你的需要
