### ISSUE TITLE
发送add_peer过程中旧leader crash，新leader有办法知道RAFT Group是否正处在add_peer过程中吗？

### ISSUE THREAD

**Issue by rhli** [brpc/braft#133]
假如旧的leader发出add_peer操作后直接crash，此刻并不知道该add_peer是否被append到log中。在这种场景下，新选出的leader是否有办法判断RAFT group是否正处在add_peer的过程中呢？

谢谢

**Comment by PFZheng** [comment]
取决于新加入的这个节点是已经完成配置变更，如果已经完成了，新leader会继续同步数据，如果没有完成配置变更，新leader不会意识到该节点的存在。
braft 实际上不是马上把节点加进去的，有一个先追日志的过程，等到日志落差小于一个margin值再进行配置变更。外围在add_peer失败的时候，应该继续重试，直至braft返回成功。

**Comment by rhli** [comment]
谢谢！虽然已经解释得很清楚了，但是我还是想确认一下：新leader选出之后，是通过list_peers()函数，就能够确定旧leader发起的add_peer()操作是否成功吗？

**Comment by PFZheng** [comment]
在on_leader_start回调之后可以用这个函数判断

**Comment by rhli** [comment]
了解，谢谢！
