### ISSUE TITLE
StateMachine::apply会等待相应的on_apply完成？

### ISSUE THREAD

**Issue by hjk41** [brpc/braft#141]
现在的情况是，我希望能够同步的等待请求完成，然后把response拿出来。但是通过log发现似乎apply返回了，但on_apply是在这之后才执行的，是不是apply其实并不会等待相应的on_apply。我想取得response只能把相应的代码放到on_done里面去？

**Comment by PFZheng** [comment]
这个其实是一个异步转同步的问题。SynchronizedClosure 可以做到这一点，继承之后，将 done 作为参数传入，apply() 之后 wait 即可。
要注意的是，如果在 on_apply 里这样做的话，会导致死锁。

**Comment by hjk41** [comment]
谢谢，已经解决。把代码都放on_done里去了，虽然代码看起来丑些，但这样更符合异步规范 ：-）
