### ISSUE TITLE
node xxx reject term_unmatched AppendEntries from yyy

### ISSUE THREAD

**Issue by hjk41** [brpc/braft#147]
从头启动一台服务器作为leader (127.0.0.1:6000)，然后加入一台follower(127.0.0.1:6001)，follower启动时--master ha_group:127.0.0.1:6000:0将自己加入到group中，然后follower上就看到如下信息：

```bash
Node joined the group as follower.
node ha_group:127.0.0.1:6001:0 reject term_unmatched AppendEntries from 127.0.0.1:6000:0 in term 2 prev_log_index 1 prev_log_term 2 local_prev_log_term 0 last_log_index 0 entries_size 0 from_append_entries_cache: 0
Configuration of this group becomes 127.0.0.1:6000:0
Configuration of this group becomes 127.0.0.1:6000:0,127.0.0.1:6001:0
Master becomes: 127.0.0.1:6000:0
```
其中"Node joined as follower"是在on_start_following()里打的，"Configuration of this group becomes..."和"Master becomes..."是在on_configuration_committed()里打的

Follower先是拒绝了一个AppendEntries，被移出group，然后又被正常的加进去了。目前看起来后续运行挺正常。为什么会有这个错误信息呢？是否会影响程序运行？

**Comment by PFZheng** [comment]
entries_size 0 这个是心跳包，当 leader 不确定一个 follower 的日志到哪儿时，会发空包试探。看这里的日志，实际上是日志不存在，response 里会随后带上本地的日志相关信息，接下来的请求就正确了

**Comment by PFZheng** [comment]
> entries_size 0 这个是心跳包，当 leader 不确定一个 follower 的日志到哪儿时，会发空包试探。看这里的日志，实际上是日志不存在，response 里会随后带上本地的日志相关信息，接下来的请求就正确了

正常情况下这个日志不需要特别关注，只有当同一个复制组有大量的这个错误日志才需要关注一下原因。

**Comment by PFZheng** [comment]
> ```shell
> Configuration of this group becomes 127.0.0.1:6000:0,127.0.0.1:6001:0
> ```

Configuration of this group becomes 127.0.0.1:6000:0
Configuration of this group becomes 127.0.0.1:6000:0,127.0.0.1:6001:0

这条日志看起来是在 on apply 配置变更的日志
