### ISSUE TITLE
Raft请求流程请教

### ISSUE THREAD

**Issue by libjjc** [brpc/braft#149]
按我的理解，客户端每次发送请求之后会到达任意的raft节点，收到请求的节点判断自身如果不是leader节点则会把请求转发给leader，leader再将请求打包成日志推送给集群内所有的flower节点。flower节点收到日志之后先cache，然后直接返回，leader判断收到日志消息的成员数量，如果大于50%，则通知客户端接收成功并通知flower进而commit那些日志信息。
问题：
1，我上面的理解是否有误？
2，leader将请求打包成日志推送给flower的过程是即时的，还是说等待下一个心跳节点，与心跳信息一同通知?
3，leader通知flower之后，需要统计flower中接收到通知的数量，那么这一步是在下一个心跳节点中统计还是额外的定时器？
4，如果这些操作都是在每一次心跳中完成，那么，一个消息从客户端发出到集群返回给客户端这中间的过程所需要的耗时就在1-2个心跳间隔。
按照raft推荐的时间150-300ms，那么每条消息延时就在300-600ms，这样我又觉得耗时长了点。所以就有了上面这些疑惑，望大神门不吝赐教啊

**Comment by PFZheng** [comment]
> 按我的理解，客户端每次发送请求之后会到达任意的raft节点，收到请求的节点判断自身如果不是leader节点则会把请求转发给leader，leader再将请求打包成日志推送给集群内所有的flower节点。flower节点收到日志之后先cache，然后直接返回，leader判断收到日志消息的成员数量，如果大于50%，则通知客户端接收成功并通知flower进而commit那些日志信息。
> 问题：
> 1，我上面的理解是否有误？
> 2，leader将请求打包成日志推送给flower的过程是即时的，还是说等待下一个心跳节点，与心跳信息一同通知?
> 3，leader通知flower之后，需要统计flower中接收到通知的数量，那么这一步是在下一个心跳节点中统计还是额外的定时器？
> 4，如果这些操作都是在每一次心跳中完成，那么，一个消息从客户端发出到集群返回给客户端这中间的过程所需要的耗时就在1-2个心跳间隔。
> 按照raft推荐的时间150-300ms，那么每条消息延时就在300-600ms，这样我又觉得耗时长了点。所以就有了上面这些疑惑，望大神门不吝赐教啊

2-4其实是raft协议原理的问题，建议阅读一下raft的论文。在实现上，第一个阶段leader给follower马上发送数据，多数节点（包括自己）给了ack，这次写就成功了；第二个阶段是心跳或者下一次的写触发的的，用来通知follower commit数据，这个时间长一些不影响延时。
“收到请求的节点判断自身如果不是leader节点则会把请求转发给leader，leader再将请求打包成日志推送给集群内所有的flower节点”。至于这一点，目前braft没有给一个通用的实现，而是交给业务自己去做，因为不同的系统的需求是有差异的，这个转发由leader做或者client做均可。

**Comment by PFZheng** [comment]
> > 按我的理解，客户端每次发送请求之后会到达任意的raft节点，收到请求的节点判断自身如果不是leader节点则会把请求转发给leader，leader再将请求打包成日志推送给集群内所有的flower节点。flower节点收到日志之后先cache，然后直接返回，leader判断收到日志消息的成员数量，如果大于50%，则通知客户端接收成功并通知flower进而commit那些日志信息。
> > 问题：
> > 1，我上面的理解是否有误？
> > 2，leader将请求打包成日志推送给flower的过程是即时的，还是说等待下一个心跳节点，与心跳信息一同通知?
> > 3，leader通知flower之后，需要统计flower中接收到通知的数量，那么这一步是在下一个心跳节点中统计还是额外的定时器？
> > 4，如果这些操作都是在每一次心跳中完成，那么，一个消息从客户端发出到集群返回给客户端这中间的过程所需要的耗时就在1-2个心跳间隔。
> > 按照raft推荐的时间150-300ms，那么每条消息延时就在300-600ms，这样我又觉得耗时长了点。所以就有了上面这些疑惑，望大神门不吝赐教啊
> 
> 2-4其实是raft协议原理的问题，建议阅读一下raft的论文。在实现上，第一个阶段leader给follower马上发送数据，多数节点（包括自己）给了ack，这次写就成功了；第二个阶段是心跳或者下一次的写触发的的，用来通知follower commit数据，这个时间长一些不影响延时。
> “收到请求的节点判断自身如果不是leader节点则会把请求转发给leader，leader再将请求打包成日志推送给集群内所有的flower节点”。至于这一点，目前braft没有给一个通用的实现，而是交给业务自己去做，因为不同的系统的需求是有差异的，这个转发由leader做或者client做均可。

在负载轻的时候，raft的延时量级差不多是（两次rpc+一次落盘的时间），这个和心跳没关系。两次rpc，一次是client到leader，一次是leader到follower

**Comment by hnwyllmm** [comment]
“leader再将请求打包成日志推送给集群内所有的flower节点“
应该不是将请求打包成日志，而是将处理结果打包发给follower节点。

**Comment by chenzhangyi** [comment]
@hnwyllmm 你的理解是错误的，请求是否需要处理也是决议的一部分，在达成决议之前，leader并不应该直接处理请求，否则拿到的结果可能是错误的.

**Comment by hnwyllmm** [comment]
那我的理解确实不是这样的，回头我再阅读一下协议文档。不过按照你的意思，请教一下，请求是要发给follower，follower回复是否可以处理？还是处理结果？我的想法还是得leader来处理，然后把结果发给follower, follower再apply。请前辈指正提点一下，谢谢！

**Comment by chenzhangyi** [comment]
在状态机层面，follower和leader**不应该有区别**，发送request或者request的变种的含义是**整个raft group**确认收到这次修改请求, 之后follower和leader通过log分别更新自己的状态机.  leader将结果返回给client
