### ISSUE TITLE
braft支持多复制组

### ISSUE THREAD

**Issue by xuefengchang** [brpc/braft#161]
关于1个braft程序中同时支持多个raft复制组，有文档或者例子可以参考吗

**Comment by PFZheng** [comment]
没有现成的文档和例子，创建多个 Node 实例就可以了

**Comment by xuefengchang** [comment]
@PFZheng 还有个问题请教下，braft里支持1个节点同时在多个复制组里吗

**Comment by Edward-xk** [comment]
支持的，这种情况下不同复制组的副本的peer_id一样（ip+port一样，idx不一定），group_id不同
