### ISSUE TITLE
两个插件同时修饰一段文字，怎么能不分割

### ISSUE THREAD

**Issue by myfCode** [brpc/braft#165]
![image](https://user-images.githubusercontent.com/20511957/65429818-6598c380-de49-11e9-8205-9c775be779b4.png)
![image](https://user-images.githubusercontent.com/20511957/65429915-8fea8100-de49-11e9-9747-fe13bfa6333b.png)
描述：
写了两个自定义按钮，插空点击生成一个blank标签包裹，选中blank标签内的内容再点击标识符的时候，会把上次的blank标签分为两个，怎样才能实现不把第一次包裹的blank标签分隔开？
代码如下：
插空：
`export const defaultInsertBlank = {
  type: 'entity',
  name: 'INSERT-BLANK',
  control: {
    text: '插空',
    title: 'insert blank',
  },
  mutability: 'MUTABLE',
  component: (props: any) => {
    return <span style={style}>{props.children}</span>;
  },
  importer: (nodeName: string, node: HTMLElement, source: string) => {
    if (nodeName === 'blank') {
      const key = node.getAttribute('key');
      return {
        mutability: 'MUTABLE',
        data: {
          key,
        },
      };
    }
    return '';
  },
  exporter: (entityObject: any, originalText: string) => {
    const data = entityObject.data || {};
    // return (
    //   <blank key={data.key} data-key={data.key}>
    //     {originalText}
    //   </blank>
    // );
    return React.createElement('blank', { datakey: data.key }, originalText);
  },
};`
标识符：
`export const defaultIdentifier = {
  type: 'entity',
  name: 'IDENTIFIER',
  control: {
    text: '标识符',
    title: 'insert identifier',
  },
  mutability: 'MUTABLE',
  component: (props: any) => {
    return <span style={style}>[{props.children}]</span>;
  },
  importer: (nodeName: string, node: HTMLElement, source: string) => {
    if (nodeName === 'identifier') {
      return {
        mutability: 'MUTABLE',
      };
    }
    return '';
  },
  exporter: (entityObject: any, originalText: string) => {
    return '[' + originalText + ']';
    // return React.createElement('blank', {}, originalText);
  },
};`

**Comment by Edward-xk** [comment]
> ![image](https://user-images.githubusercontent.com/20511957/65429818-6598c380-de49-11e9-8205-9c775be779b4.png)
> ![image](https://user-images.githubusercontent.com/20511957/65429915-8fea8100-de49-11e9-9747-fe13bfa6333b.png)
> 描述：
> 写了两个自定义按钮，插空点击生成一个blank标签包裹，选中blank标签内的内容再点击标识符的时候，会把上次的blank标签分为两个，怎样才能实现不把第一次包裹的blank标签分隔开？
> 代码如下：
> 插空：
> `export const defaultInsertBlank = { type: 'entity', name: 'INSERT-BLANK', control: { text: '插空', title: 'insert blank', }, mutability: 'MUTABLE', component: (props: any) => { return <span style={style}>{props.children}</span>; }, importer: (nodeName: string, node: HTMLElement, source: string) => { if (nodeName === 'blank') { const key = node.getAttribute('key'); return { mutability: 'MUTABLE', data: { key, }, }; } return ''; }, exporter: (entityObject: any, originalText: string) => { const data = entityObject.data || {}; // return ( // <blank key={data.key} data-key={data.key}> // {originalText} // </blank> // ); return React.createElement('blank', { datakey: data.key }, originalText); }, };`
> 标识符：
> `export const defaultIdentifier = { type: 'entity', name: 'IDENTIFIER', control: { text: '标识符', title: 'insert identifier', }, mutability: 'MUTABLE', component: (props: any) => { return <span style={style}>[{props.children}]</span>; }, importer: (nodeName: string, node: HTMLElement, source: string) => { if (nodeName === 'identifier') { return { mutability: 'MUTABLE', }; } return ''; }, exporter: (entityObject: any, originalText: string) => { return '[' + originalText + ']'; // return React.createElement('blank', {}, originalText); }, };`

貌似发错地方了？
