### ISSUE TITLE
能否创建单个非leader节点？

### ISSUE THREAD

**Issue by walterzhaoJR** [brpc/braft#169]
能否创建单个非leader节点，quorum可以大于1.
其实我的场景是这样，要将一个raft node（A）加到已有的raft group（G1）中，但是要求A不能是leader状态，这和要怎么实现呢？

**Comment by walterzhaoJR** [comment]
单个raft node创建出来后状态就是leader了

**Comment by hnwyllmm** [comment]
改一下代码，加个配置，不允许发起pre_vote和vote就可以了

**Comment by killme2008** [comment]
bootstrap 方法

**Comment by hnwyllmm** [comment]
bootstrap又不能让节点加入到其它组

**Comment by killme2008** [comment]
bootstrap 是启动一个空白节点，不会选举，然后可以加入。 bootstrap 也可以带着数据启动，比如你手动拷贝了 snapshot。

**Comment by hnwyllmm** [comment]
@killme2008 
`int bootstrap(const BootstrapOptions& options) {
    global_init_once_or_die();
    NodeImpl* node = new NodeImpl();
    const int rc = node->bootstrap(options);
    node->shutdown(NULL);
    node->join();
    node->Release();  // node acquired an additional reference in ctro.
    return rc;
}`
bootstrap之后不就直接退出了吗？

**Comment by walterzhaoJR** [comment]
按这样后边这个节点还能被选为leader吗

**Comment by killme2008** [comment]
@killme2008 sorry，我的描述有问题，这样是搭建了一个节点框架，后续你正常启动就可以了，他不会去选举自己为 leader。  看下 BootstrapOptions 吧。

**Comment by killme2008** [comment]
@walterzhaoJR  可以参考我在 sofa-jraft 的回答 https://github.com/sofastack/sofa-jraft/issues/95

**Comment by walterzhaoJR** [comment]
那把他加入到已有的一个raft group中，难道这个节点就和其他的节点性质一样了吗

**Comment by walterzhaoJR** [comment]
@killme2008 @hnwyllmm 谢谢，我再看看

**Comment by walterzhaoJR** [comment]
禁止了将自己选举为leader和pre_vote
