### ISSUE TITLE
问题请教，备机异常时，主回复客户端失败还是异常

### ISSUE THREAD

**Issue by hnwyllmm** [brpc/braft#170]
场景描述：
两个节点的raft group, A leader, B follower。
client向A发送请求，A将数据转发给B，同时落地数据，B将数据落地，宕机，未回复A。
A由于超时未收到B的回复，向client发送失败，还是异常的消息？

**Comment by Edward-xk** [comment]
我理解这种case下，由于B在回复A之前宕机，所以A上无法commit这条log; 过一段时间后，A会因为检查到存活节点不到多数而step_down成为follower，此时会向client回复一个EPERM的错误码（但这条log可能在B重启后被apply, 业务层若对结果有强依赖可以加一些检查的逻辑）

**Comment by hnwyllmm** [comment]
嗯，看样只能由客户端来控制了。
