### ISSUE TITLE
removePeer操作完成后不会回调on_configuration_committed吗

### ISSUE THREAD

**Issue by walterzhaoJR** [brpc/braft#175]
removePeer操作完成后不会回调on_configuration_committed吗？

**Comment by walterzhaoJR** [comment]
或者就是说被删除的follower节点怎么知道自己被删除掉了

**Comment by chenzhangyi** [comment]
目前的结点变更是二阶段的，第二阶段只会发给新的集合的结点，所以被remove的结点本身是不会通过raft协议本身获取自己被remove的结果.

这是因为:
 1. 对于raft协议来说，被remove结点本身可能已经出于不可用状态，要维护`remove命令`的到达本身要么需要维护的状态太多，要么本身做不到可靠.
 1. raft协议本身不负责placement, 应该有外部的master或者commander等角色去触发, 在普遍的应用中，基本上是有一个master节点等到remove callback之后去处理这些结点(比如发remove_replica到指定的server上)

**Comment by walterzhaoJR** [comment]
谢谢，我也看到了协议是两阶段的，第二阶段只会发给新的集合的结点。
第二点中“在普遍的应用中，基本上是有一个master节点等到remove callback之后去处理这些结点(比如发remove_replica到指定的server上)”这块没有太明白，应为我们现在的做法是在leader节点上去主动调用remove_peer来删掉某个replica，你意思是说应该在要删掉的replica上进行remove_peer操作，在其他节点上通过on_configuration_committed来做其他逻辑吗？
