### ISSUE TITLE
NodeImpl::list_peers(std::vector<PeerId>* peers)的一些疑问？

### ISSUE THREAD

**Issue by walterzhaoJR** [brpc/braft#179]
![image](https://user-images.githubusercontent.com/22393698/69030906-c987d480-0a13-11ea-97db-20fd6c74152d.png)
这里对非leader节点直接返回是基于什么考虑的呢？
![image](https://user-images.githubusercontent.com/22393698/69030958-e6240c80-0a13-11ea-9ac4-99426e044eb7.png)
这个地方又没有做什么区分？

**Comment by htner** [comment]
我猜，是因为
1. nodeimpl::list_peers主要是给cli_service逻辑使用的，从一致性考虑，只允许从主里获取数据，只允许从主里变更
2. describe是builtin_service_impl使用，将所有的内部状态打印出来，返回所有的信息并没有什么问题

**Comment by Edward-xk** [comment]
> 我猜，是因为
> 
> 1. nodeimpl::list_peers主要是给cli_service逻辑使用的，从一致性考虑，只允许从主里获取数据，只允许从主里变更
> 2. describe是builtin_service_impl使用，将所有的内部状态打印出来，返回所有的信息并没有什么问题

嗯，是这样的

**Comment by Edward-xk** [comment]
如果还有进一步的问题再open吧
