### ISSUE TITLE
启动新节点的时候，leader没用snapshot去同步follower。

### ISSUE THREAD

**Issue by pdu** [brpc/braft#23]
测试步骤如下：
1，先启动一台节点，并设置为leader
2，插入1000条数据，每条数据大小26KB，看日志有3到4个log segment产生
3，做snapshot
4，再插入1000条数据，每条数据大小为26KB，看日志有3到4个log segment产生
5，新启动一个节点，加入raft group成为leader
6，leader同步数据到follower，用的全是这些log segemnt，没有用snapshot

有2个问题：
1，什么时候leader会用snapshot去同步数据到follower呢？感觉上述测试里面，更倾向是snapshot + log segment
2，做了snapshot之后，为什么没有删除旧的log segment？删除的机制是怎么样的？

**Comment by ipconfigme** [comment]
leader同步使用的是snpashot+log segment。但是braft的实现是保留最近2个snapshot之后的log segment，为了确保一些频繁snapshot在install snapshot的时候拉不到对应的log。所以leader上做完一次snapshot，依然会看到有之前的log segment，这个时候再做一次snapshot就会出发最前的3-4个log segment删除。

**Comment by pdu** [comment]
@ipconfigme 谢谢！重新做了一次snapshot，看到了现象。
