### ISSUE TITLE
如何知道新节点已经同步了所有的数据呢？

### ISSUE THREAD

**Issue by pdu** [brpc/braft#24]
测试的对这个场景有疑问。
1，先有一个节点，自己是leader，写入了很多数据
2，加入一个节点，leader对这个节点同步数据
3，同时还在向leader写入数据

如果场景是对读只要弱一致，什么时候才能知道新节点已经同步了所有的历史数据，对外提供服务呢？

**Comment by ipconfigme** [comment]
Leader和Follower之间定义一种Protocol可以实现，比如Follower定期查询Leader上last applied index，跟本地的last applied index进行比较，这样就可以判断是否apply了全部的日志。

**Comment by pdu** [comment]
@chenzhangyi 好的，谢谢！

我看到有2次on_configuration_committed调用，第一次是只有leader，第二次是包含了leader和自己。

**Comment by pdu** [comment]
@ipconfigme 只想要知道节点起来之后有没有加载历史数据就够了。可以在client端拿到整个raft group的last applied index，client端自己选择也可以。

@chenzhangyi 你说的这个方式只在特定场景下是有效的，当一个新节点起来，原先的leader不需要同步数据过来的时候，就不会调用on_configuration_committed。这样逻辑就不统一了，用起来很奇怪。

**Comment by chenzhangyi** [comment]
加入新节点，肯定会有节点变更日志的。

2018-05-09 16:15 GMT+08:00 Peng Du <notifications@github.com>:

**Comment by pdu** [comment]
在应用需要识别以下三种情况：

- 节点作为raft group里面的第一个节点起来，没有数据，可以对外提供服务
- 节点重启，加载本地的snapshot和log到应用层后，可以对外提供服务
- 新起节点加入raft group，从leader同步了snapshot和log并且加载到应用层后，可以对外提供服务

从braft的实现中，如果找到一个标记，说可以对外提供服务了呢？

**Comment by pdu** [comment]
我目前是打算把applied_id放出去：https://github.com/brpc/braft/blob/master/src/braft/log_manager.h#L198

1. 外围的cluster manager会跟所有的raft node发心跳，心跳里面会包含最新的applied_id，raft node也会把自己当前的applied_id返回去
2. raft node起来的时候，初始init = false，当自己applied_id >= 心跳的applied_id就改init = true
3. cluster manager对一个raft group初始的applied_id = 0

各位大神有什么建议吗？

**Comment by pdu** [comment]
是否用这个值代替applied_id也可以呢？
https://github.com/brpc/braft/blob/master/src/braft/raft.h#L145

是不是不管有没有snapshot，只要log，raft state machine都会触发on_apply()？
如果是这样的话，我就不用把log_manager里面的_applied_id信息放出来了。

**Comment by ipconfigme** [comment]
>> 是不是不管有没有snapshot，只要log，raft state machine都会触发on_apply()？
是的，只要有log就会有on_apply的回调。

看上面的讨论已经超出最初的判断新节点是否同步最新数据的问题了。你提到的cluster manager的思路，其实跟我上面说的leader和follower之间定义protocol其实类似，这个cluster manager的工作可以由leader来执行，可以是leader向follower推，也可以是follower向leader拉。

对于你说的三种场景：
场景1是ok的。
场景2如果你说的是单节点的group，其中的唯一节点重启，这样的话是ok的，否则不能确定重启节点的数据跟最新的数据差异。
场景3新加入的节点见我们上面的讨论。

**Comment by pdu** [comment]
@ipconfigme 谢谢。我现在的做法是在on_apply和on_snapshot_load的时候记录下当前的applied_index，通过其他的protocol传进来一个applied_index_threshold，大于threshold就判断为可以对外服务。

我关掉ticket了。
