### ISSUE TITLE
a raft node is crashed, the leader is empty?

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#25]
when a raft node is crashed, select leader is empty, why no fllower node become the leader？

**Comment by pdu** [comment]
how many nodes you have in the raft group? only more than half of the nodes are healthy, they can auto elect the new leader.

**Comment by xuxiping** [comment]
2 nodes, one is crashed, there are no leader.

**Comment by pdu** [comment]
according to the definition of raft protocol, it's the right behavior. if you want the other node to be the leader, you have to call "reset_peers" interface to reset the raft group to contains only 1 node.

**Comment by xuxiping** [comment]
thks
