### ISSUE TITLE
Bug：在特定条件下重启node失败

### ISSUE THREAD

**Issue by pdu** [brpc/braft#26]
复现步骤：
1. 启动节点1，初始conf为：host1:port1:0，设置节点1为leader
2. 启动节点2，初始conf为：host1:port1:0
3. 节点2加入节点1作为follower
4. 重启节点2，一定初始化失败

原因：
1. 节点2因为初始conf跟自己的地址不匹配，所以voted_for的值是":0:0"
2. 重启初始化的时候，PeerId加载":0:0"的时候出错

https://github.com/brpc/braft/blob/master/src/braft/configuration.h#L61
   
    int parse(const std::string& str) {
        reset();
        char ip_str[64];
        if (2 > sscanf(str.c_str(), "%[^:]%*[:]%d%*[:]%d", ip_str, &addr.port, &idx)) {
            reset();
            return -1;
        }
        if (0 != butil::str2ip(ip_str, &addr.ip)) {
            reset();
            return -1;
        }
        return 0;
    }

sscanf对":0:0"的case处理有问题，unittest里面也缺少相应的case：https://github.com/brpc/braft/blob/master/test/test_configuration.cpp#L30

BTW：需要发PR修复吗？如果需要，流程是什么？

**Comment by pdu** [comment]
@ipconfigme 好的，谢谢。

在k8s的场景下，一个raft group里面的所有节点会给一个统一的init_conf配置，如果只给第一个配置其他留空，不算一个很好的k8s风格，所以我做了上述的测试用例。

**Comment by ipconfigme** [comment]
如果使用统一的init_conf的话，建议使用{host1:port1:0, host2:port2:0}作为init_conf

**Comment by Edward-xk** [comment]
reopen this issue if there is any more question
