### ISSUE TITLE
编译braft是要放到brpc目录里面吗？

### ISSUE THREAD

**Issue by zhousysu** [brpc/braft#29]
`zhou@ubuntu:~/brpc/braft/build$ cmake .. && make
CMake Error at CMakeLists.txt:58 (message):
  Fail to find brpc

-- Configuring incomplete, errors occurred!
See also "/home/zhou/brpc/braft/build/CMakeFiles/CMakeOutput.log".
See also "/home/zhou/brpc/braft/build/CMakeFiles/CMakeError.log".
zhou@ubuntu:~/brpc/braft/build$ 
`

**Comment by chenzhangyi** [comment]
不需要， 如果brpc不是按照在公共目录的话， 需要在cmake中指定library_path和include_path

**Comment by HappyKL** [comment]
请问下最后这个问题怎么解决的啊？

**Comment by darrenwang00** [comment]
> 请问下最后这个问题怎么解决的啊？

set(BRPC_INCLUDE_PATH "your_path/brpc/include")
set(BRPC_LIB "your_path/brpc/lib")
直接设置一下路径， 我这么解决的

**Comment by huntinux** [comment]
> > 请问下最后这个问题怎么解决的啊？
> 
> set(BRPC_INCLUDE_PATH "your_path/brpc/include")
> set(BRPC_LIB "your_path/brpc/lib")
> 直接设置一下路径， 我这么解决的

set(BRPC_INCLUDE_PATH "your_path/brpc/output/include")
set(BRPC_LIB "your_path/brpc/output/lib")
