### ISSUE TITLE
为什么node.h/node.cpp里有两个方法都叫apply啊

### ISSUE THREAD

**Issue by Borelset** [brpc/braft#30]
明明功能完全都不一样，而且一个apply要掉用另一个，为什么要弄成一样的名字。。。人类为什么要互相伤害。。。

**Comment by Borelset** [comment]
@ipconfigme 
不是这个问题啊，我知道有个Node还有个NodeImpl，Node里有个apply方法对应了NodeImpl中的一个apply方法，问题是NodeImpl里面还有另一个apply方法。。。

**Comment by ipconfigme** [comment]
一个是外部接口，一个是内部通过无锁队列的内部批量优化接口。如果只是使用只需要关注单个参数的那个apply外部接口即可，另一个是实现的优化。
