### ISSUE TITLE
关于jepsen测试的两个问题

### ISSUE THREAD

**Issue by phylips** [brpc/braft#32]
1.atomic_test后面多了一个空格，运行的时候应该会报错
c/exec "./atomic_test "

2.atomic_set! get! cas!这些函数都是在db node上执行实际binary的。这样在做网络分区测试的时候，client本身也会受影响。放在控制节点是否更合理？

**Comment by Leviathan1995** [comment]
@phylips 你说的这两点都没有问题，仔细看下代码和Jepsen

**Comment by phylips** [comment]
你说的没有问题是指Jespen可以正常跑吗？
我在jepsen环境上运行看到的现象是可以正常跑。最终是会报：
Everything looks good! ヽ(‘ー`)ノ

我的场景是这样的，参考braft中的jepsen代码写法写了一个简单测试，在jepsen环境上运行了下。
1.关于第一个问题，是在把代码里面异常try catch部分去掉后发现的，去掉之后我这边跑jepsen会报这个错误：
INFO [2018-06-01 12:05:05,929] jepsen worker 0 - jepsen.util 41 :info   :cas    [2 4]   indeterminate: sudo -S -u root bash -c "cd /root/jepsen_work_dir; \"./atomic_test \" -jepsen_op cas -reg_val 2 -reg_new_val 4 -reg_id 0" returned non-zero exit status 127 on jepsen_control_1. STDOUT:


STDERR:
bash: ./atomic_test : No such file or directory

确认了下，目录下是有这个文件的。为了验证是后面的空格导致的，把后面的空格去掉错误就没有了。你可以再确认下。如果说你们的环境上去掉try catch后也能跑过那就比较奇怪了，再问一句这个空格是干啥的，能去掉吗？

2.关于第二个问题是说放在控制节点执行是否更加合理？目前这种做法(我理解是c/on是会ssh到db node上执行binary进行测试，如果理解有误请指出)也能跑，但是会对测试造成影响。

具体来说如果做网络分区测试，比如我们随机选择一台机器断开，那么如果c/on的刚好是被断开的那个机器上。那么在这个机器上发出的请求会超时。虽然不影响正确性，但是会造成这个client的timeout。

另外如果上面的理解有问题希望可以指出具体的问题。多谢。
