### ISSUE TITLE
选举过程中出现 参数错误日志

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#34]
W0607 19:49:05.888779 32357 node.cpp:1276] node 0e3382b2-7c31-45df-b50c-98cebdb90986:172.24.156.86:8011:0 request PreVote from 172.24.156.86:8012:0 error: [E22][0.0.0.0:8012][E22]Invalid argument

**Comment by ipconfigme** [comment]
查看172.24.156.86:8012，可能是这个节点的状态机出错了
