### ISSUE TITLE
选举过程中出现下面错误， 是啥原因呢，怎么避免

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#35]
- W0607 20:52:56.610767 16557 node.cpp:1228] node d0b4e2f4-db42-4f54-a8d4-8776af3af85a:172.24.156.91:8012:0 received invalid PreVoteResponse from 172.24.156.86:8012:0 state not in STATE_FOLLOWER but CANDIDATE
- W0607 20:52:56.614214 16562 node.cpp:1157] node d0b4e2f4-db42-4f54-a8d4-8776af3af85a:172.24.156.91:8012:0 received invalid RequestVoteResponse from 172.24.156.86:8012:0 state not in CANDIDATE but LEADER

**Comment by ipconfigme** [comment]
收到Response略慢，这个WARNING可以不用关心
