### ISSUE TITLE
状态机出现下面错误，what can i do?

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#36]
W0607 19:48:16.614872 31763 node.cpp:1119] node 0e3382b2-7c31-45df-b50c-98cebdb90986:172.24.156.86:8012:0 got error={type=StateMachineError, error_code=10002, error_text=`StateMachine meet critical error when applying one  or more tasks since index=6417014, none'}

**Comment by chenzhangyi** [comment]
说明业务状态机出现异常了， 看下问题在哪里吧.
