### ISSUE TITLE
快照同步出错

### ISSUE THREAD

**Issue by wind-zhang** [brpc/braft#38]
启动3个节点，选主（128是主节点）正常，后续停128，剩下两个节点（129,130），重新启动128后，其中一个节点出现如下错误信息：

I0613 14:25:00.753657  9132 /home/zhangxf/github/braft/src/braft/replicator.cpp:623] node licenserpc:192.168.109.130:8100:0 send InstallSnapshotRequest to 192.168.109.128:8100:0 term 10 last_included_term 10 last_included_index 3 uri remote://192.168.109.130:8100/-19242672944717
I0613 14:25:00.753845  9132 /home/zhangxf/github/braft/src/braft/replicator.cpp:668] received InstallSnapshotResponse from licenserpc:192.168.109.128:8100:0 last_included_index 3 last_included_term 10 error: [E112]Not connected to 192.168.109.128:8100 yet

**Comment by ipconfigme** [comment]
看上去130拿到了leader，向128发送rpc的过程中128出问题了。参考：
https://github.com/brpc/brpc/blob/master/docs/cn/error_code.md

**Comment by wind-zhang** [comment]
上面的问题解决了，是我自身机器防火墙问题，目前还不清楚，之前一直连通的怎么突然又连不通。
另外还想请教一个问题在 braft::StateMachine  里面如果我的业务操作 定义为一个对象指针，这种情况下如何对快照进行加载和读取，是否 只保存和加载这个指针就行了，还是需要记载和读取 指针指向的内存部分？

**Comment by wind-zhang** [comment]
类似下面那样的 m_pBusiManager ，on_apply回调的时候会调用m_pBusiManager里面的操作或者更改m_pBusiManager的数据成员， 这种情况怎么进行快照保存 
class License : public braft::StateMachine
{
public:
 .......
.........
 private:
    braft::Node* volatile _node;
    butil::atomic<int64_t> _leader_term;
     CBusiManager    *m_pBusiManager;  //业务指针
}

**Comment by ipconfigme** [comment]
> 是否只保存和加载这个指针就行了，还是需要记载和读取 指针指向的内存部分？

需要把指针指向的内存内容进行dump和load，因为进程可能会重启，只保存指针没啥用的。
