### ISSUE TITLE
braft线程模型问题

### ISSUE THREAD

**Issue by wgtdkp** [brpc/braft#39]
你们在 https://github.com/brpc/braft/blob/master/docs/cn/benchmark.md 中提到通过“**尽可能的降低锁临界区大小， 关键路径上采用lock-free/wait-free算法.**”来提升性能。但是NodeImpl的实现中，几乎每一个主要的raft协议过程的开头都要加锁**_mutex**。那么这意味着，两个客户端请求无法并行执行，而是通过抢锁来串行化。我看到你们有node_manager，用来管理多个raft node。应该是想用多个raft node的来达到并行化，但是没有看到相关的例子。那么，一个server（core number = N）节点部署多少个raft node呢？N/4？N/2？还是N, 2N呢？在raft node较多时，是否会面临线程频繁调度的问题？

**Comment by ipconfigme** [comment]
> 关键路径上采用lock-free/wait-free算法

这个是指写本地log，log复制，log apply等这样的地方

> 两个客户端请求无法并行执行

这个主要是把提交串行，之后的同步逻辑不在mutex中

> 那么，一个server（core number = N）节点部署多少个raft node呢？N/4？N/2？还是N, 2N呢？

不需要这么N/4或者是N/2，一个node并不需要完全占用某些thread。这个根据自己的需求而定，我们的存储系统中每个Server部署上千的raft node。

> 在raft node较多时，是否会面临线程频繁调度的问题？
braft是基于底层的brpc及其bthread，每个raft node不绑定pthread，所以这个raft node数量跟线程调度没啥关系

**Comment by wgtdkp** [comment]
>这个主要是把提交串行，之后的同步逻辑不在mutex中

提交串行化是raft本身保证的，我指的并行性是实现层面的。如，request0的handleAppendEntriesResponse能否和request1的handleClientRequest并行执行。因为这两个过程都需要mutex保护。所以我认为做不到。当然，繁重的IO操作不在mutex之内，我想要确认的是raft的协议逻辑这部分（剔除IO），并不能做到我上面说的并行化。串行执行如下：
|| request0.handleClientRequest || request1.handleClientRequest || request0.handleAppendEntriesResponse || request1.handleAppendEntriesResponse ......

> 不需要这么N/4或者是N/2，一个node并不需要完全占用某些thread。这个根据自己的需求而定，我们的存储系统中每个Server部署上千的raft node。

当然是不需要独占线程。但是考虑极限情况下，1000 requests分属1000 raft nodes，显然1000 个raft nodes 不能并发执行各自的HandleClientRequest。既然实际的并发度不可能达到1000，那么部署上千的raft node应该只是应用的需要吧？比如为了限制partition size。
```c++
if (bthread::execution_queue_start(&_apply_queue_id, NULL, execute_applying_tasks, this) != 0) {
    LOG(ERROR) << "Fail to start execution_queue";
    return -1;
}
```
这段 `NodeImpl::Init` 中的代码。对于1000个apply_queue,实际是由多少个worker线程执行的呢？是由bthread自己动态调整的？

**Comment by ipconfigme** [comment]
> 我想要确认的是raft的协议逻辑这部分（剔除IO），并不能做到我上面说的并行化。

对于一个raft node的RAFT协议状态机是串行的，对于RAFT实现的其他部分中做并行化。

> 但是考虑极限情况下，1000 requests分属1000 raft nodes，显然1000 个raft nodes 不能并发执行各自的HandleClientRequest。

同上，mutex是针对的一个raft node，不同的raft node可以并发

> 对于1000个apply_queue,实际是由多少个worker线程执行的呢？是由bthread自己动态调整的？

execq按需启动bthread执行task，这块可以参考bthread和execq的文档https://github.com/brpc/brpc/blob/master/docs/cn/bthread.md
https://github.com/brpc/brpc/blob/master/docs/cn/execution_queue.md

**Comment by wgtdkp** [comment]
不同的raft的node当然可以。但是并发度的上限是硬件线程数。谢谢你的解答。
