### ISSUE TITLE
严重：braft停止错误，

### ISSUE THREAD

**Issue by wind-zhang** [brpc/braft#40]
请帮忙看看是什么情况引起这种错误，需要怎样处理。

I0621 11:22:57.423517 21025 /home/zhangxf/github/braft/src/braft/node.cpp:846] node licenserpc:192.168.109.128:8100:0 shutdown, current_term 3 state LEADER
I0621 11:22:57.423598 21025 /home/zhangxf/github/braft/src/braft/replicator.cpp:1152] Fail to find the next candidate
I0621 11:22:57.423629 21025 src/brpc/server.cpp:1033] Server[braft::RaftStatImpl+indigo::LicenseServiceImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is going to quit
W0621 11:22:57.423711 21036 src/brpc/policy/baidu_rpc_protocol.cpp:257] Fail to write into fd=11 SocketId=8589934851@192.168.109.128:33055@8100: Got EOF
W0621 11:22:57.423711 21034 src/brpc/policy/baidu_rpc_protocol.cpp:257] Fail to write into fd=12 SocketId=8589934976@192.168.109.128:33060@8100: Got EOF
W0621 11:22:57.424027 21036 src/brpc/policy/baidu_rpc_protocol.cpp:257] Fail to write into fd=13 SocketId=8589934977@192.168.109.128:33062@8100: Got EOF
W0621 11:22:57.424027 21034 src/brpc/policy/baidu_rpc_protocol.cpp:257] Fail to write into fd=14 SocketId=8589935104@192.168.109.128:33065@8100: Got EOF

**Comment by ipconfigme** [comment]
看日志Server调用了Stop

Got EOF可以参考brpc的文档：
https://github.com/brpc/brpc/blob/master/docs/cn/server.md

不确定你说的问题是哪个

**Comment by wind-zhang** [comment]
看了下参考文档，说是 客户端连接池或者短连接会发生这种情况，
我这边是短连接的，定时向server查询一个信息，但是即使 发生了EOF的情况，我的客户端想再次连接连接不上了，还有我的服务端也没办法停下来，查看进程状态直接是睡眠状态，没办法接收任何退出信息号，只能强制Kill掉，这个有点不合理。  或者是我客户端设置不对，？
还有一个问题，客户端如何使用长连接来与服务端通信

**Comment by ipconfigme** [comment]
这些问题都不是braft相关的，而是brpc相关的，建议仔细阅读：
https://github.com/brpc/brpc/blob/master/docs/cn/client.md
https://github.com/brpc/brpc/blob/master/docs/cn/server.md

再看一下brpc中的一些example代码

**Comment by ipconfigme** [comment]
看上去是服务端代码的问题，可以看一下server的日志什么的，看看done是否都有run，再看看这个文档：
https://github.com/brpc/brpc/blob/master/docs/cn/server_debugging.md
从builtin service中看一下各种内部状态是否有异常

**Comment by wind-zhang** [comment]
检查过了，能接受的done都是会执行run的，
今天再核查了一遍：
1、启动服务端，启动客户端可以连接上一切ok,
2、停止客户端，间隔5分钟 再启动客户端提示：
W0625 14:58:20.221749 56576 ./client/lic_client.cpp:79] Fail to send request to 192.168.109.128:8100:0 : [E1008]Reached timeout=10000ms @192.168.109.128:8100
3、查看服务端状态：
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:8100            0.0.0.0:*               LISTEN      56012/./license_ser 
tcp        0      0 192.168.109.128:8100    192.168.109.1:8200      ESTABLISHED 56012/./license_ser 
tcp        0      0 192.168.109.128:8100    192.168.109.128:40606  CLOSE_WAIT  56012/./license_ser 

4、此时停止服务端：
license.shutdown();
  server.Stop(0);
  license.join();  --在这里阻塞了 ，具体是 braft::Node.join() 
  server.Join();

5、如果停止客户端**马上又启动连接服务端是可以连接的 ，**比较诡异，服务端检查过了，是仿照braft-example-counter的服务端代码写的。

**Comment by ipconfigme** [comment]
上面并没有任何server端有价值的日志等信息，建议从builtin service中的一些监控项目入手。RPC超时如果done都有run的话，看看是不是有一些pthread阻塞操作导致没有worker可以执行了。
