### ISSUE TITLE
snapshot interval

### ISSUE THREAD

**Issue by tigerzhang** [brpc/braft#41]
braft 带的 3 个 example 默认的 snapshot_interval 都是 30s，相对其他的 raft 库，snapshot 比较频繁。

snapshot 过程中，raft 的性能明显会降低，braft 在生产环境里，snapshot interval 配置多少？也是 30s 这么频繁吗？

请教下 braft 是怎么考虑的。

**Comment by ipconfigme** [comment]
这个根据业务来定吧，example只是为了演示而已。基本上看snapshot interval内写log的量，再根据介质计算追log的时间，使得冷重启的时间控制在你们接收的时间范围内。
