### ISSUE TITLE
状态机Apply时出错如何处理？

### ISSUE THREAD

**Issue by RobitYadda** [brpc/braft#42]
问题描述：
       比如有3个节点，1个Leader(a),2个Follower(b,c)，同一条log，a和b都可以正常执行，c执行时出错(比如磁盘满了或者其它原因)，那么该如何处理呢，是否需要把该节点从group中移除？我看例子里是调用set_error_and_rollback这个函数，但是好像并不能解决问题。我看一些raft的讲解中，也没有对这部分进行描述。

**Comment by ipconfigme** [comment]
这个时候看业务场景，比如元信息meta类的，可能是报警然后人工介入处理；比如存储场景，可能是尝试踢掉这个副本，然后再补一个副本。

**Comment by RobitYadda** [comment]
谢谢，请教下调用set_error_and_rollback是会重新apply这条日志吗？

**Comment by ipconfigme** [comment]
set_error_and_rollback是会回滚日志，但是之后不能再apply了，需要修复状态机之后才能再apply
