### ISSUE TITLE
braft有计划对pipeline的支持吗？

### ISSUE THREAD

**Issue by yongs207** [brpc/braft#45]
当前的Replicator::_send_entries是在发送完成后的回调中再次发送下一个message，这样会让所有消息的发送全部是串行的，是否考虑支持pipeline的处理？还是内部实际做个这样的优化，发现效果不好才没有进行处理？

**Comment by ipconfigme** [comment]
近期会merge到github上

**Comment by yongs207** [comment]
期待中...

**Comment by leonwu327** [comment]
最近有将对pipeline的支持merge到github上的计划吗？

**Comment by yongs207** [comment]
pipeline的合并具体是什么时候？如果自己实现会导致和社区的版本分离的，改动有点大呀

**Comment by ipconfigme** [comment]
计划下周合入

**Comment by PFZheng** [comment]
已经合如 @leonwu327
