### ISSUE TITLE
braft冷启动的处理时间过长

### ISSUE THREAD

**Issue by yongs207** [brpc/braft#46]
当前的braft的实现中，冷启动时会从没有快照的日志数据全部重新回放，而这样的处理在一些场景下其实并不是十分科学，比如用braft结合rocksdb实现一个简单的nosql，如果这些日志数据已经被执行，其实就没有回放的必要了，这个处理的过程中，是否可以在SM类中添加一个get_checkpoint的虚函数，当node启动加载时，更加获得的checkpoint的值来和快照的执行点两者一起来确认日志回放的起始点，这样就可以缩短冷启动的时间

**Comment by ipconfigme** [comment]
之前考虑过类似的方案，比如传递committed_index的hint来加速启动，但是这个只适用于snapshot和base数据一起的场景。这个时候需要持久化committed_index，如果用户不能保证每条log都持久化committed_index的话，再使用上面的这个重放优化的时候会出问题，比如持久化记录的committed_index比实际的committed_index小一些，如果正好log中有类似inc这样的log的话，会导致最终的value重放之后不对，这种方案用户容易用错。
如果你的场景snapshot和base可以放一起，并且在业务上你能够保证重放不影响一致性的话，最简单的是on_apply执行null，直接跳过记录的committed_index之前的log。如果真的有必要，我们再考虑增加一些skip的机制。

**Comment by yongs207** [comment]
确实场景是snapshot和base放到一起的，但这个机制应该和这个没有直接关系，保存committed_index只是间歇的保存，只要在下次加载时，存储引擎会去读取最后已保存的committed_index，由这个commited_index来保证重放的数据内容。同时实现时保存的commited_index保证和启动一条数据记录做为一个事务下去，这样就不会出现问题。这里不去回放日志是应该快照的时间间隔不可能特别频繁，而当数据压力比较大时，会挤压过多的数据记录，这样回放，即使不去执行，有时也会出现时间比较长的问题

**Comment by lilithliu1** [comment]
我们这边实现了一个快速启动的方案，在收到shut_down信号之后保存一份applied_index。系统在重启的时候，applied_index之前的指令执行null操作。这种是优雅退出的快速启动。非优雅退出由于没有保存applied index，没有执行上述操作，所以我们结合rocksdb也做了非优雅退出之后的快速启动方案。具体可参考我们的项目：https://github.com/baidu/BaikalDB

**Comment by yongs207** [comment]
我们实际中也是用的以上方法，只是觉得在框架层面支持会更好
