### ISSUE TITLE
MultiRAFT 静默模式的疑问 

### ISSUE THREAD

**Issue by yongs207** [brpc/braft#47]
静默模式
RAFT的Leader向Follower的心跳间隔一般都较小，在100ms粒度，当复制实例数较多的时候，心跳包的数量就呈指数增长。通常复制组不需要频繁的切换Leader，我们可以将主动Leader Election的功能关闭，这样就不需要维护Leader Lease的心跳了。复制组依靠业务Master进行被动触发Leader Election，这个可以只在Leader节点宕机时触发，整体的心跳数就从复制实例数降为节点数。社区还有一种解决方法是MultiRAFT，将复制组之间的心跳合并到节点之间的心跳。

这里的主动Leader Election的功能关闭是指使用reset_election_timeout_ms将超时时间变长吗？如果是会有什么负面影响？
Master进行被动触发Leader Election这里是指重新设置选主超时时间开始选主操作吗？
Leader节点宕机触发，是符合感知Leader节点宕机的呢？通过业务Master吗？这里的业务Master是需要在每个节点上都有有一个leader吗？如果是业务Master的leader出现漂移怎么处理？

**Comment by ipconfigme** [comment]
这个静默模式后来没有做

**Comment by ipconfigme** [comment]
这个multi-raft有些不同的解释，cockroachdb那个是上面说的心跳合并，这个braft没有实现；业界也有一些multi-raft理解是一个程序支持多个raft复制组，这个braft是支持的。

**Comment by yongs207** [comment]
这里的主要疑问在braft支持一个程序支持多个raft复制组，当时如果不进行心跳合并的处理下，当raft复制组比较多时，会不会存在性能问题？

**Comment by xuefengchang** [comment]
关于一个braft程序支持多个raft复制组，这个有文档或者例子可以参考吗 @ipconfigme

**Comment by GOGOYAO** [comment]
> 这个multi-raft有些不同的解释，cockroachdb那个是上面说的心跳合并，这个braft当前没有实现，后续会考虑实现；业界也有一些multi-raft理解是一个程序支持多个raft复制组，这个braft是支持的。

心跳合并目前有计划么
