### ISSUE TITLE
Failover 是否有测试数据？

### ISSUE THREAD

**Issue by lingji** [brpc/braft#5]

**Comment by ipconfigme** [comment]
是业务自己的client和server之间的failover吗？或者是说leader多长时间变更？

**Comment by lingji** [comment]
leader多长时间变更，业务才能切换？这也是一个很关键的因素。

**Comment by ipconfigme** [comment]
不知道理解你的问题，从我们的系统的配置条件下，大概两周会有一次主从切换，切换时间在200ms以内。

**Comment by lingji** [comment]
我自己测测试，谢谢！
