### ISSUE TITLE
Stepdown timer not be processed ?

### ISSUE THREAD

**Issue by demiaowu** [brpc/braft#50]
Hi，搜索全部代码，发现 StepdownTimer，在 `become_leader()` 时 start 之后，就没有在处理过了，感觉 StepdownTimer 貌似没有进行处理，在 StepdownTimer run() 函数加日志发现，节点成 Leader 之后，一直触发 StepdownTimer timeout，目前这块逻辑没有完善还是 ？
下面给的打印日志，
>I0712 19:56:23.524367 52422 /root/data/braft-master/example/block/server.cpp:398] Node becomes leader
E0712 19:56:28.523725 52432 /root/data/braft-master/src/braft/node.cpp:2475] StepdownTimer timeout 5000
E0712 19:56:33.525770 52430 /root/data/braft-master/src/braft/node.cpp:2475] StepdownTimer timeout 5000
E0712 19:56:38.525977 52432 /root/data/braft-master/src/braft/node.cpp:2475] StepdownTimer timeout 5000
E0712 19:56:43.526221 52419 /root/data/braft-master/src/braft/node.cpp:2475] StepdownTimer timeout 5000
I0712 19:56:48.370575 52428 /root/data/braft-master/example/block/server.cpp:337] Saving snapshot to ./data/snapshot/temp/data
I0712 19:56:48.375188 52428 /root/data/braft-master/src/braft/snapshot.cpp:589] Deleting ./data/snapshot/snapshot_00000000000000000001
I0712 19:56:48.375222 52428 /root/data/braft-master/src/braft/snapshot.cpp:595] Renaming ./data/snapshot/temp to ./data/snapshot/snapshot_00000000000000000001
I0712 19:56:48.375242 52428 /root/data/braft-master/src/braft/snapshot_executor.cpp:210] snapshot_save_done, last_included_index=1 last_included_term=2
E0712 19:56:48.526525 52419 /root/data/braft-master/src/braft/node.cpp:2475] StepdownTimer timeout 5000
E0712 19:56:53.526775 52419 /root/data/braft-master/src/braft/node.cpp:2475] StepdownTimer timeout 5000
E0712 19:56:59.222747 52428 /root/data/braft-master/src/braft/node.cpp:2475] StepdownTimer timeout 5000  

修改代码：
```
void StepdownTimer::run() {
+    LOG(ERROR) << "StepdownTimer timeout" << " " << _timeout_ms;
    _node->handle_stepdown_timeout();
}
```
_timeout_ms 改成了 public 成员变量

参考设计文档描述
> Leader 在 ElectionTimeout 内没有写多数成功，通过 logic clock 检查实现（1个ElectionTimeout内会有10个HeartBeat）  

StepdownTimer 应该是长时间写没成功，判断 peer 是不是还是活的，或者自己是不是被隔离，然后决定是否 Stepdown，但是在代码中并没有看到这部分逻辑 ？

**Comment by chenzhangyi** [comment]
现在是通过周期性检查多数节点的应答时间来做的.

**Comment by demiaowu** [comment]
这样可以通过主动的 Step down 来避免 stale read。但是这仅仅保证了 read 是在 leader 上，但是在 examples/block 的例子中 read的例子中，来有看到如何避免 stale read 的逻辑，因为即使在 leader 上 read，但是 leader 上可能会存在已经 commit 但是没有 apply 的 log entry，理论上需要等到所有 commit 的 log entry 被 apply 之后才能返回 read，但是在 block 的例子中是直接 read data 然后返回的

**Comment by demiaowu** [comment]
看了代码，结合 #15 回复，以及 examples/atomic 例子发现是直接通过将 read 也走一遍 raft log 来实现的，不知道未来支持计划是 ？？

不过看代码，貌似可以利用 StepdownTimer 计时器来实现 Lease read 貌似很方便，StepdownTimer 本身就实现了 Leader 身份 lease 的确认 ？？
