### ISSUE TITLE
ERROR: unknown command line flag 'crash_on_fatal_log'

### ISSUE THREAD

**Issue by bolanbujing** [brpc/braft#54]
我拉下代码，brpc没有安装到公有目录，但是在braft的cmake里指定了brpc的目录，编译通过了，./run_client.sh 和 ./run_server.sh 都报错了 ERROR: unknown command line flag 'crash_on_fatal_log'

**Comment by ipconfigme** [comment]
这个flag跟宏BRPC_WITH_GLOG互斥
