### ISSUE TITLE
log index ?

### ISSUE THREAD

**Issue by demiaowu** [brpc/braft#55]
在 SegmentLogStorage 中，log entry 的 index 实际上可以通过 log 命的后缀推到出来，那为什么还需要特意的保存 `first_log_index` 到 `log_meta` 文件中，感觉没有必要，还是有特殊设计考量 ？
```
#define BRAFT_SEGMENT_OPEN_PATTERN "log_inprogress_%020ld"
#define BRAFT_SEGMENT_CLOSED_PATTERN "log_%020ld_%020ld"
```

**Comment by chenzhangyi** [comment]
两个层次的事情.
segment要等到整个文件的log都不再需要才会被删， first log index可能处于第一个segment的中间.

**Comment by demiaowu** [comment]
这样可以减少不必要的日志回放~

**Comment by chenzhangyi** [comment]
减少回放不是主要目的，逻辑上被truncate的日志是不可信的, 之后不应该再被读出来

**Comment by demiaowu** [comment]
但是 raft 本身是要求所有操作都是幂等，在重启的时候重放日志，会存在重复 apply 的操作，毕竟 raft 没有记录 apply index，所以这里应该不会有问题，还麻烦帮忙看看 #57

**Comment by chenzhangyi** [comment]
raft从来没要求过操作幂等， log的apply是exactly once

**Comment by demiaowu** [comment]
嗯嗯，对，也是 raft 确实没有要求操作幂等，只是自己场景所有操作是幂等，所以忽略了这一点。

不过在 committed 的 log 不一定成功返回 client 端，client 端能做的只有重试，这个时候依照论文里的方案：
> The solution is for clients to assign unique serial numbers to every command. Then, the state machine tracks the latest serial number processed for each client, along with the associated response. If it receives a command whose serial number has already been executed, it responds immediately without re-executing the request

但是实现这个方案应该并不容易，而且要配合客户端来做 

而且线性一致性语义，也没有定义这种行为：
> linearizable semantics (each operation appears to execute instantaneously, exactly once, at some point between its invocation and its response)
实际上线性一致性强调的是 inv 和 res 之间被原子和瞬间的执行一次，但是 client 并没有返回成功，那么可能就是超时错误，那么这里的 res 就是超时出错，所以，client 重试就是一个新的 inv 和 res，那么这样，从 Op 的 history 来看，重试并没有违背线性一致性的语义。只是从 client 端的业务角度来看，这个 op 如果不是幂等的，那么就不能被执行两次

**Comment by ipconfigme** [comment]
重启重放log并不存在重复apply，重启还是根据之前snapshot中记录的last_included_index之后的log重放。你如果把snapshot和base数据搞一起才会出现你说的重放问题，如无特殊需要不建议这么做。

**Comment by demiaowu** [comment]
仍有两个疑问 ？

1. snapshot meta 中已经存放了 last_log_index 保证，apply 不会有 log 重复 apply，为什么还要保存一个 first_log_index ?

2. 你说的 snapshot 和 base 数据搞一起，是不是就是 snapshot 和 base 都是同一份数据，就像现在的 example/block，执行打快照实际上只是创建了一个硬链接，并没有真正的拷贝数据 ？

3. 你说的 '把snapshot和base数据搞一起才会出现你说的重放问题，如无特殊需要不建议这么做' ？是指 在 #46 讨论的，snapshot 和 base 数据放在一起，为了减少 braft 冷启动的时间，需要保存 committed_index，但是不能保证持久化的 committed index 总是最新的，那么就有可能出现重复 apply 的情况。个人理解，如果 snapshot 和 base 数据搞在一起，那么必须应用本身的所有 log 都是幂等的才行，不然根据 snapshot meta 中 last_log_index 来重放日志，依然是会有重复 apply

**Comment by ipconfigme** [comment]
snapshot和base使用同一份数据的话，不是要log幂等，是要log重放之后数据是最终一致的。

**Comment by demiaowu** [comment]
如果 log 幂等，log 重放之后数据不就是最终一致的

**Comment by ipconfigme** [comment]
重启的时候重放log是基于之前的snapshot，这块逻辑没有问题，需要保持幂等，也不需要什么log重放保证最终一致性，因为本身模型就能保证一致性。对于snapshot和base在一起的case，需要的log重放的最终一致性。像block的那个模型，模型本身重放就可以保证最终一致性，没有必要实现log的幂等。
还是那个建议，如无需要，不要将snapshot和base放一起。
