### ISSUE TITLE
jepsen test model bug

### ISSUE THREAD

**Issue by demiaowu** [brpc/braft#57]
在当前的 jepsen 的测试中 atomic get 当 `read nil` 的时候返回的是 0， 而 jepsen 测试使用的 model  `:model     (model/cas-register)`，这个 model `read nil` 返回的是 nil
```
(defn cas-register
  "A compare-and-set register"
  ([] (cas-register nil))
  ([value] (CASRegister. value)))
```
会造成 jepsen 测试中，如果第一个是 read，那么返回 `0`，将会和 model 输出不一致，model 输出是 `nil`

**Comment by ipconfigme** [comment]
恩，atomic的example收到没有的key查询返回0。感谢贡献的pull request
