### ISSUE TITLE
慢节点快照同步问题

### ISSUE THREAD

**Issue by yongs207** [brpc/braft#59]
当前的快照是以时间为自动触发的（也可以在外部主动触发），并且在进行快照时是使用applied_index作为快照的结束index,而在我们的raft中实际只要两个节点（总共3副本情况）同步完成就会将applied_index设置为对应的值，这样在实际情况中如果出现其中有一个节点数据同步比较慢，和其他两节点有一定差距，这样会leader在后续的同步中就会需要install_snapshot.
上述的实现存在一个问题，如果落后的节点稍微落后其他两个节点也有可能操作snapshot的安装，因为快照后会进行truncate_prefix这样前面的index就会变得无法获取，从而重新发送全部快照，而这个成本是非常搞的，且可能在实际情况中频繁出现。
这里在进行快照时，是否可以已保留多少条log作为快照的依据，这样就能让用户更具应用场景来调节日志的大小和快照频率及解除延时导致的频繁获取日志的问题

**Comment by ipconfigme** [comment]
实际上braft已经多留了一个snapshot周期的log，比如snapshot2完成之后才会删除snapshot1之前的log

**Comment by yongs207** [comment]
@ipconfigme 谢谢即使回复，查看了set_snapshot的代码确实是这样的，应该是我们测试的过程中快照过于频繁导致的，准备在set_snapshot中添加一个配置项来确定至少保留多长的日志数

**Comment by chenzhangyi** [comment]
加上保留多久的日志是解决不了这个问题的， 这个问题的本质在于install snapshot之后log已经被删除了。在snapshot非常频繁的情况下，确定多长的日志数是一个非常困难的事情. 
@Edward-xk 之前有个计划中feature是保留多少个snapshot，可能更适合解决这个问题.
