### ISSUE TITLE
Use of flatbuffer or capnproto instead of protobuf

### ISSUE THREAD

**Issue by yashhema** [brpc/braft#67]
Hello
Is there any particular reason for using protobuf instead of flatbuffer or capnproto
If I want to switch to flatbuffer or capnproto , how do you suggest as going on updating the code (ie I want to do step by step , so I can test at each step), any suggestions are welcome

**Comment by demiaowu** [comment]
I think that you only just rewrite the rpc service, because you just replace the  serialization/deserialization framework , but the protocol of raft have no modify

**Comment by lanyunzhang** [comment]
@yashhema  Have you implemented brpc to use the flatbuffer protocol ？

**Comment by yashhema** [comment]
Hello
No, I didn't work
Regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hustqy** [comment]
mark
