### ISSUE TITLE
如何程序控制使某个节点成为leader？

### ISSUE THREAD

**Issue by wherwh** [brpc/braft#68]
场景：2个节点,分别称为1,2号节点。 调试1号节点，希望1号节点作为leader.

可以通过先启动1号，再启动2号来实现。
但如何通过程序控制方式使1号成为leader呢？

尝试的方法有：
。1号定时执行node.apply：不起作用
。如果发现自己不是leader,就node.reset_election_timeout_ms： 很少能成功

请问应该怎么做?

**Comment by demiaowu** [comment]
1. 有 transfer leader 接口，在 cli.h/cli.cpp 中，直接写代码调相关的接口即可
2. 还提供了 cli 的包装 braft_cli 的命令行工具，使用参见文档https://github.com/brpc/braft/blob/master/docs/cn/cli.md

**Comment by PFZheng** [comment]
raft 协议本身无法保证一定某个节点抢到主. 一般外围做一个定期检测的程序/逻辑，然后通过  transfer leader 来完成切主.

**Comment by wherwh** [comment]
谢谢 @demiaowu @PFZheng
