### ISSUE TITLE
raft_mutex_t为什么使用pthread_mutex而不使用bthread_mutex

### ISSUE THREAD

**Issue by leonwu327** [brpc/braft#69]
//#define USE_BTHREAD_MUTEX
这里为什么要注释掉呢，raft_mutex_t为什么使用pthread_mutex而不使用bthread_mutex

**Comment by PFZheng** [comment]
这是一个疏忽，默认应该使用 bthread mutex

**Comment by chenzhangyi** [comment]
几点原因， 
1. bthread_mutex会造成上下文切换， 对于raft这种比较底层的调用可能会对调用方造成surprise，可能会导致死锁
2. raft里面的临界区基本都是优化过的，本身的contention不大，用bthread_mutex优势不大
