### ISSUE TITLE
是否可以提供bazel的build方式？brpc是有bazel的build的。

### ISSUE THREAD

**Issue by pdu** [brpc/braft#7]
因为开发环境已经升级protobuf3了，但是编译brpc+braft需要protobuf2，折腾起来很麻烦。

如果用bazel的话，可以指定源码的版本，比较方便。

**Comment by jamesge** [comment]
pb3可以兼容pb2，别用新类型，开头加上syntax="proto2";即可

**Comment by pdu** [comment]
@jamesge 谢谢！
