### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#72]
为啥braft里面所有 brpc请求所用的Channel 都没有复用？

**Comment by demiaowu** [comment]
1. braft 并不是所有的 brpc channel 没有被复用，例如 Replicator 里面的 sending_channel
2. braft 中的 example 中的 rpc channel 都没被复用，可能是因为仅仅是 example，所以为了编码方便，直接就没有复用 channel

**Comment by xuxiping** [comment]
route_table 中
