### ISSUE TITLE
如果想要把snapshot存在S3上，应该怎样实现比较好呢？

### ISSUE THREAD

**Issue by pdu** [brpc/braft#75]
应用场景是这样的：如果snapshot存储在类似EFS的分布式文件系统中，当需要做scaling up的时候，会一起去读写snapshot，会导致对EFS的流量很高。所以想要把snapshot写入S3中，那样成本会更低。
怎样去实现比较方便呢？因为我看到FileAdaptor中的接口有offset之类的，担心用S3这种直接就存储整个文件的，不是很好去实现。snapshot meta是可以继续存在EFS中的。

**Comment by ipconfigme** [comment]
可以不用，让SnapshotReader和SnapshotWriter相对处理好就行

**Comment by pdu** [comment]
@ipconfigme 是说直接改里面的实现吗？Reader和Writer直接访问object storage？感觉是否直接开放一个针对Snapshot存储的Object storage interface会好一些？那样我application level和raft内部都可以用同一套object storage的client code了。

**Comment by ipconfigme** [comment]
不用啊，定制一个S3 SnapshotStorage注册到braft中，实现自己的SnapshotWriter和SnapshotReader

**Comment by pdu** [comment]
明白了，多谢！
