### ISSUE TITLE
raft group 目录删除

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#77]
1、创建一个raft组， 添加数据， 停止程序。
2、删除raft 本地目录(log, raft_meta, snapshot)，再次启动程序，braft会再次创建raft 目录。
3、进行数据添加，此时返回值直接为 空，没有报错，不会走到 StateMachine::on_apply。

**Comment by Edward-xk** [comment]
可以再描述详细点吗？上面的各步操作是针对复制组的哪些节点或是所有节点？重启后成功选主了吗？

**Comment by demiaowu** [comment]
单个节点，你删除了所有的数据，那么重启，首先这个节点会发起选举，选举成功之后，正常可以提供服务，只是之前的数据都不见了。理论上你的第 3 步，向复制组 apply 一些 Op，如果选举成功了，Op 能正常服务，反之，因为不是 leader，会返回 `EPERM` 的错误~
