### ISSUE TITLE
节点成为leader时有可能没有apply所有日志到状态机导致client读到旧的状态

### ISSUE THREAD

**Issue by niukuo** [brpc/braft#81]
当某个节点成为leader时，有可能状态机中的数据还是旧的。这个时候如果client来访问，有可能会看到旧的状态，导致无法保证数据的一致性，尤其是on_apply执行的比较慢的时候。有没有什么建议如何避免发生这种情况？

**Comment by niukuo** [comment]
测试了一下这时候写操作是不会成功的

**Comment by gdyang1990** [comment]
> 当某个节点成为leader时，有可能状态机中的数据还是旧的。这个时候如果client来访问，有可能会看到旧的状态，导致无法保证数据的一致性，尤其是on_apply执行的比较慢的时候。有没有什么建议如何避免发生这种情况？



> 测试了一下这时候写操作是不会成功的

如果你需要强一致读语义，应该等on_leader_start回调之后再对外提供读服务，on_leader_start是在on_apply完所有committed log之后才回调的

**Comment by niukuo** [comment]
暂时找到一种解决办法（不确定对不对）：on_leader_start被调用后才提供服务

**Comment by niukuo** [comment]
> > 当某个节点成为leader时，有可能状态机中的数据还是旧的。这个时候如果client来访问，有可能会看到旧的状态，导致无法保证数据的一致性，尤其是on_apply执行的比较慢的时候。有没有什么建议如何避免发生这种情况？
> 
> > 测试了一下这时候写操作是不会成功的
> 
> 如果你需要强一致读语义，应该等on_leader_start回调之后再对外提供读服务，on_leader_start是在on_apply完所有committed log之后才回调的

恩和我猜想的一样 感谢！
