### ISSUE TITLE
后续版本有没有考虑将AppendEntry改为异步调用

### ISSUE THREAD

**Issue by yongs207** [brpc/braft#83]
如果LogStorage或SnapshotStorage需要采用SPDK时，异步是更为理想性能更高的方式，而当前的appendEntry为同步的调用，后续有没有计划改造同时支持异步，如果改造成异步使用SPDK，会不会与bthread的机制产生冲突

**Comment by PFZheng** [comment]
disk thread 本身已经在一个单独的 bthread 线程里面执行。至于你所说期望的这种全异步方式，改造起来有一定的难度，因为逻辑上对顺序性有要求（例如，后面的 log 完成落盘意味着前面的完成落盘，truncate 和 write 并发也容易出问题）。
braft 支持定制 log storage。如果需要引入 SPDK，可以考虑自己实现 log storage。在定制的 log storage append_entries 的接口中，配合 SynchronizedClosure，可以避免 hung 住 pthread 线程，大概类似于这样：

int append_entries(const std::vector<LogEntry*>& entries) {
    ....
    SynchronizedClosure closure;
    // XXX 发起写，完成调用 closure->Run()
    closure.wait(); // 类似于协程，这里会主动让出 pthread 线程，直至Run() 将其唤醒
    ....
}
