### ISSUE TITLE
raft 节点处理CANDIDATE 阶段，一直无法选举leader

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#86]
![default](https://user-images.githubusercontent.com/38487648/50327106-977ea180-0528-11e9-9bd5-146379925998.png)

**Comment by xuxiping** [comment]
上图中为啥会有votedfor 0.0.0.0:0:0 这个 PeerId?

**Comment by xuxiping** [comment]
我看了源代码， 有个地方判断日志时出问题了，[代码](https://github.com/brpc/braft/blob/6371de9d465e471fe48dba590dd00c831c242135/src/braft/node.cpp#L1859)， 这里日志出问题，有哪些原因导致呢？

**Comment by Edward-xk** [comment]
> 我看了源代码， 有个地方判断日志时出问题了，[代码](https://github.com/brpc/braft/blob/6371de9d465e471fe48dba590dd00c831c242135/src/braft/node.cpp#L1859)， 这里日志出问题，有哪些原因导致呢？

一种case是vote过程中follower写了新日志导致投票失败，我们线上环境出现过这种异常case，你这里具体原因要仔细分析日志，才能确认是不是相同的case

**Comment by xuxiping** [comment]
> 
> 
> > 我看了源代码， 有个地方判断日志时出问题了，[代码](https://github.com/brpc/braft/blob/6371de9d465e471fe48dba590dd00c831c242135/src/braft/node.cpp#L1859)， 这里日志出问题，有哪些原因导致呢？
> 
> 一种case是vote过程中follower写了新日志导致投票失败，我们线上环境出现过这种异常case，你这里具体原因要仔细分析日志，才能确认是不是相同的case

我好像找到原因了， 因为我调用了 NodeImpl::read_committed_user_log 这个函数， 此函数性能导致
