### ISSUE TITLE
raft节点移除后程序崩溃，堆栈信息如下，求解

### ISSUE THREAD

**Issue by weingithub** [brpc/braft#88]
Program terminated with signal 11, Segmentation fault.
#0  0x00007f1daf27c4c9 in InsertBefore (e=0x55ce799abab8, this=0x7f1d84bae2a0) at brpc/src/butil/containers/linked_list.h:97
97          e->previous_->next_ = this;
(gdb) bt
#0  0x00007f1daf27c4c9 in InsertBefore (e=0x55ce799abab8, this=0x7f1d84bae2a0) at brpc/src/butil/containers/linked_list.h:97
#1  Append (e=0x7f1d84bae2a0, this=0x55ce799abab8) at brpc/src/butil/containers/linked_list.h:171
#2  bthread::wait_for_butex (arg=0x7f1d84bae2a0) at brpc/src/bthread/butex.cpp:514
#3  0x00007f1daf294b4e in bthread::TaskGroup::sched_to (pg=pg@entry=0x7f1d9271a3b0, next_meta=next_meta@entry=0x55ce727ec580) at brpc/src/bthread/task_group.cpp:623
#4  0x00007f1daf2968e2 in sched_to (next_tid=<optimized out>, pg=0x7f1d9271a3b0) at brpc/src/bthread/task_group_inl.h:75
#5  bthread::TaskGroup::run_main_task (this=this@entry=0x55ce71d0b800) at brpc/src/bthread/task_group.cpp:147
#6  0x00007f1daf2924fe in bthread::TaskControl::worker_thread (arg=0x55ce718e8400) at brpc/src/bthread/task_control.cpp:73
#7  0x00007f1daeeb0e25 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f1dac91734d in clone () from /lib64/libc.so.6
(gdb) f 0
#0  0x00007f1daf27c4c9 in InsertBefore (e=0x55ce799abab8, this=0x7f1d84bae2a0) at brpc/src/butil/containers/linked_list.h:97
97          e->previous_->next_ = this;
(gdb) p *e
$1 = {previous_ = 0x0, next_ = 0x0}
(gdb) f 1
#1  Append (e=0x7f1d84bae2a0, this=0x55ce799abab8) atbrpc/src/butil/containers/linked_list.h:171
171         e->InsertBefore(&root_);
(gdb) p root_
$2 = {previous_ = 0x0, next_ = 0x0}

**Comment by weingithub** [comment]
不知道是否是raft删除不当，还是bthread使用不当？

**Comment by chenzhangyi** [comment]
跑下asan看下， 这种通常是内存被写坏了

**Comment by weingithub** [comment]
修改上层逻辑，不再出现该coredump了。
