### ISSUE TITLE
NodeImpl::read_committed_user_log 占用大量io导致，服务堵塞！

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#89]
https://github.com/brpc/braft/blob/725242dec9a9bbcf7a663282bcc65f1ac68568f8/src/braft/node.h#L208

**Comment by chenzhangyi** [comment]
@Edward-xk

**Comment by Edward-xk** [comment]
> [braft/src/braft/node.h](https://github.com/brpc/braft/blob/725242dec9a9bbcf7a663282bcc65f1ac68568f8/src/braft/node.h#L208)
> 
> Line 208 in [725242d](/brpc/braft/commit/725242dec9a9bbcf7a663282bcc65f1ac68568f8)
> 
>  butil::Status read_committed_user_log(const int64_t index, UserLog* user_log);

能提供稍微详细点的信息吗，比如你们怎么调用这个接口的，还有服务阻塞时的pstack信息？
