### ISSUE TITLE
how to define the conf --when run the example counter.

### ISSUE THREAD

**Issue by asland-system** [brpc/braft#9]
when i run the example counter,i got some problem like "".  i think it is  caused by undefine conf. so how do i define the conf ? please tell me ,thank you.
 DEFINE_string(conf, "", "Initial configuration of the replication group");

the error :
node Counter:127.0.0.1:8100:0 term 1 start pre_vote
W0320 16:40:10.782916 13281 /home/robin/github/braft/src/braft/node.cpp:1305] node Counter:127.0.0.1:8100:0 can't do pre_vote as it is not in 192.168.109.128:8100:0,192.168.109.128:8101:0,192.168.109.128:8102:0

**Comment by asland-system** [comment]
i'm a newer programer and i'm very hopely  to try the brafter

**Comment by chenzhangyi** [comment]
Did you run counter_server via run_server.sh?

**Comment by asland-system** [comment]
yes , use run_server.sh to run

**Comment by asland-system** [comment]
the server's log :
c/braft/node.cpp:1294] node Counter:127.0.0.1:8101:0 term 1 start pre_vote
W0320 17:26:39.528064 18213 /home/robin/github/braft/src/braft/node.cpp:1305] node Counter:127.0.0.1:8101:0 can't do pre_vote as it is not in 192.168.109.128:8100:0,192.168.109.128:8101:0,192.168.109.128:8102:0

**Comment by asland-system** [comment]
my steps:
1. git clone 
2. use command  "mkdir build && cd build && cmake .. && make" to compile the braft
3. compile the counter : cd  example/counter && cmake . && make 
4. run the counter:
./run_server.sh
./run_client.sh

i don't know whether there has some wrong steps or wrong parameters.

**Comment by chenzhangyi** [comment]
The ip via `hostname -i` in run_server.sh is different with the ip via butil::my_ip() in the program. To simply solve this issue, you can rewrite the IP variable in run_server.sh to '127.0.0.1' directly.  The root cause is hard to figured out, more information (kernel version, linux distribution, output of `hostname -i' etc) may help to find the issue.

**Comment by asland-system** [comment]
it's just like what you said,  i can test the counter now. thank you.
