### ISSUE TITLE
同步最新braft之后，出现大量如下警告

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#92]
![default](https://user-images.githubusercontent.com/38487648/50500369-d01ffd00-0a8b-11e9-8073-5cb7a62c2924.png)

**Comment by chenzhangyi** [comment]
@doc001

**Comment by PFZheng** [comment]
@xuxiping 确认一个事情，是否开启了 pipeline。raft_max_parallel_append_entries_rpc_num > 1（replicator.cpp 中）时意味着开启了，默认没有开启。如果开启了，check 一下 raft_enable_append_entries_cache 和 raft_max_append_entries_cache_size 这两个参数 (node.cpp 中)。开启 pipeline 的时候，并发的请求容易出现乱序，建议打开 cache。

**Comment by PFZheng** [comment]
如果没有开启 pipeline 的话，需要看下是不是中间有切主，term_unmatched 这个切主后的 stale 请求也会触发
