### ISSUE TITLE
raft_mutex_t目前默认采用pthread_mutex, 如果锁范围内发生了bthread线程切换是否存在问题

### ISSUE THREAD

**Issue by leonwu327** [brpc/braft#93]
比如在SnapshotExecutor::do_snapshot函数中，on_snapshot_save在raft_mutex_t锁范围内, 在example的block中，on_snapshot_save调用了bthread_start_urgent(&tid, NULL, save_snapshot, arg);应该当前线程执行save_snapshot, 启动一个新线程执行当前的上下文。
另外在pthread_mutex中如果存在bthread_mutex也可能发生线程切换，我的理解是只有存在切换的现象，应该可能导致死锁的封签，bthread的线程池有限，如果线程池中被请求锁占满了，如果pthread_mutex所范围中有发生bthread切换，会导致没有bthread线程解锁，从而导致死锁，不知道是否存在这样的问题？

**Comment by PFZheng** [comment]
on_snapshot_save 真正的工作建议异步执行，不应该在调用的地方处理太长时间，这个同步处理过程会hung 住其它日志的 apply。
bthread_mutex 发生线程切换时，意味着已经产生锁冲突，有一个地方正在执行冲突的逻辑，等该处释放了锁，会继续处理。一般情况下不会因此导致死锁。

**Comment by leonwu327** [comment]
现在braft中的raft_mutex_t默认使用的是pthread_mutex, 是不是可能出现这样一个现象，所有的线程都是handle_append_entries_request函数在请求NodeImpl 里面的_mutex， 而_mutex目前的持有者已经被切走了，现在线程池中已经没有线程没有切回来，导致死锁？
另外，braft中的raft_mutex_t如果改用bthread::Mutex貌似一启动就coredump，这个是什么原因导致的呢
谢谢！
