### ISSUE TITLE
可不可以对NodeOption里面几个参数做下详细说明

### ISSUE THREAD

**Issue by xuxiping** [brpc/braft#94]
snapshot_file_system_adaptor
snapshot_throttle

**Comment by PFZheng** [comment]
snapshot_file_system_adaptor：这个主要是方便用户 hook install snapshot 过程中的读写。在默认的实现中，snapshot 的文件都要求在 snapshot 文件夹下，install snapshot 传输的过程就是普通文件读写，业务没有机会截获这个过程。但是，有时候用户用了 rocksdb 之类的存储引擎，snapshot 的操作可以不做任何额外的工作，但是读写的时候就需要做 hook，这个时候可以利用 snapshot_file_system_adaptor。

snapshot_throttle：这个是 install snapshot 限速的接口。在很多时候，一个机器上有非常多的 raft 复制组，如果同时都在执行 install snaposhot，势必会影响用户 IO。特别是 balance 的操作，它的优先级应该是比较低的。这种情况下，可以利用 snapshot_throttle 做一些限速。默认的实现比较简单，但是已有的接口应该足够用户定制 per-disk 或 per-rg 的限速。
