### ISSUE TITLE
on_configuration_committed semantic issues

### ISSUE THREAD

**Issue by demiaowu** [brpc/braft#96]
当前 StateMachine on_configuration_committed 接口语义是 apply 配置变更日志的时候调用
```
    // Invoked when a configuration has been committed to the group
    virtual void on_configuration_committed(const ::braft::Configuration& conf);
```
但是在 `void FSMCaller::do_snapshot_load(LoadSnapshotClosure* done) ` 加载快照的时候调用了，感觉不符合 on_configuration_committed 的语义。snapshot 中的配置信息应该通过 on_load_snapshot 接口去暴露，而不是 on_configuration_committed
```
    ......
    if (meta.old_peers_size() == 0) {
        // Joint stage is not supposed to be noticeable by end users.
        Configuration conf;
        for (int i = 0; i < meta.peers_size(); ++i) {
            conf.add_peer(meta.peers(i));
        }
        _fsm->on_configuration_committed(conf);
    }
    ......
```

**Comment by ipconfigme** [comment]
on_snapshot_load是最开始的接口，使用中有些场景需要暴露configuration，才有了on_configuration_committed接口。正如你所说这个接口主要是apply configuration change日志采用的，但是snapshot中都是applied的日志，用这个on_configuration_committed来传递configuration也是ok的。
